<a href="https://colab.research.google.com/github/anshumanshukl1605/question-practice-/blob/master/session_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/gemini-code-1791019120405.txt")

FileNotFoundError: [Errno 2] No such file or directory: '/content/gemini-code-1791019120405.txt'

In [ ]:
df

     name       city  math_score  attendance_pct
0  Ananya  Bengaluru          78              92
1   Rahul     Mumbai          55              78
2   Priya    Chennai          92              88
3    Sana       Pune          88              95
4  Vikram  Bengaluru          64              60
5   Karan     Mumbai          71              85
6   Meera    Chennai          95              91
7   Arjun       Pune          49              70

In [ ]:
df["name"]

0    Ananya
1     Rahul
2     Priya
3      Sana
4    Vikram
5     Karan
6     Meera
7     Arjun
Name: name, dtype: object

In [ ]:
df[["name", "math_score"]]

     name  math_score
0  Ananya          78
1   Rahul          55
2   Priya          92
3    Sana          88
4  Vikram          64
5   Karan          71
6   Meera          95
7   Arjun          49

In [ ]:
# Select the "city" column from the DataFrame and display it.

df["city"]

0    Bengaluru
1       Mumbai
2      Chennai
3         Pune
4    Bengaluru
5       Mumbai
6      Chennai
7         Pune
Name: city, dtype: object

In [ ]:
# Select the "math_score" column from the DataFrame and display it.

df["math_score"]

0    78
1    55
2    92
3    88
4    64
5    71
6    95
7    49
Name: math_score, dtype: int64

In [ ]:
# Select the "name" and "math_score" columns together and display the result.
df[["name","math_score"]]

     name  math_score
0  Ananya          78
1   Rahul          55
2   Priya          92
3    Sana          88
4  Vikram          64
5   Karan          71
6   Meera          95
7   Arjun          49

In [ ]:
# Select the row with index label 3 and display all its information.
df.loc[3]

name              Sana
city              Pune
math_score          88
attendance_pct      95
Name: 3, dtype: object

In [ ]:
# Select the "math_score" of the student whose index label is 3.
df.loc[3,"math_score"]

np.int64(88)

In [ ]:
# Select students with index labels 1 through 4 and display all their information.
df.loc[1:4]

     name       city  math_score  attendance_pct
1   Rahul     Mumbai          55              78
2   Priya    Chennai          92              88
3    Sana       Pune          88              95
4  Vikram  Bengaluru          64              60

In [ ]:
# Select the third row of the DataFrame using its position.
df.iloc[2]

name                Priya
city              Chennai
math_score             92
attendance_pct         88
Name: 2, dtype: object

In [ ]:
# Select the math score of the student at row position 5.
df.iloc[5,2]

np.int64(71)

In [ ]:
# Find the number of rows and columns in the DataFrame.
df.shape

(8, 4)

In [ ]:
# Display the first 3 rows of the DataFrame.
df.head(3)

     name       city  math_score  attendance_pct
0  Ananya  Bengaluru          78              92
1   Rahul     Mumbai          55              78
2   Priya    Chennai          92              88

In [ ]:
# Display a concise summary of the DataFrame, including column names, non-null values, and data types.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            8 non-null      object
 1   city            8 non-null      object
 2   math_score      8 non-null      int64
 3   attendance_pct  8 non-null      int64
dtypes: int64(2), object(2)
memory usage: 388.0+ bytes

In [ ]:
# Generate summary statistics for the numeric columns in the DataFrame.
df.describe()

       math_score  attendance_pct
count    8.000000        8.000000
mean    74.000000       82.375000
std     17.204651       12.176529
min     49.000000       60.000000
25%     61.750000       76.000000
50%     74.500000       86.500000
75%     89.000000       91.250000
max     95.000000       95.000000

In [ ]:
# Sort the DataFrame by "math_score" in ascending order.
df_sorted = df.sort_values(by="math_score", ascending=True)
print(df_sorted)

     name       city  math_score  attendance_pct
7   Arjun       Pune          49              70
1   Rahul     Mumbai          55              78
4  Vikram  Bengaluru          64              60
5   Karan     Mumbai          71              85
0  Ananya  Bengaluru          78              92
3    Sana       Pune          88              95
2   Priya    Chennai          92              88
6   Meera    Chennai          95              91

In [ ]:
# Find the top 3 students based on their math_score.
a= df.sort_values(by="math_score",ascending=False)
print(a.head(3))

    name     city  math_score  attendance_pct
6  Meera  Chennai          95              91
2  Priya  Chennai          92              88
3   Sana     Pune          88              95

In [ ]:
# Display the last 2 students from the DataFrame.
df.tail(2)

    name     city  math_score  attendance_pct
6  Meera  Chennai          95              91
7  Arjun     Pune          49              70

In [ ]:
# Find the student with the lowest math_score.

a = df.loc[df["math_score"].idxmin()]
print(a)

name              Arjun
city               Pune
math_score           49
attendance_pct       70
Name: 7, dtype: object

In [ ]:
# Sort the students by city in ascending order, and within each city,
# sort them by math_score in descending order.

a = df.sort_values(by=["city", "math_score"], ascending=[True, False])
print(a)

     name       city  math_score  attendance_pct
0  Ananya  Bengaluru          78              92
4  Vikram  Bengaluru          64              60
6   Meera    Chennai          95              91
2   Priya    Chennai          92              88
5   Karan     Mumbai          71              85
1   Rahul     Mumbai          55              78
3    Sana       Pune          88              95
7   Arjun       Pune          49              70

In [8]:
import pandas as pd

data = {
    "city": ["Delhi", "Mumbai", "Delhi", "Noida", "Mumbai"],
    "orders": [120, 200, 150, 90, 180],
    "revenue": [12000, 25000, 18000, 9000, 22000]
}

df = pd.DataFrame(data)
print(df.head)
print(df.shape)
print(df.info)

<bound method NDFrame.head of      city  orders  revenue
0   Delhi     120    12000
1  Mumbai     200    25000
2   Delhi     150    18000
3   Noida      90     9000
4  Mumbai     180    22000>
(5, 3)
<bound method DataFrame.info of      city  orders  revenue
0   Delhi     120    12000
1  Mumbai     200    25000
2   Delhi     150    18000
3   Noida      90     9000
4  Mumbai     180    22000>

In [9]:
df = pd.DataFrame(data)

print(df.head())

print(df.shape)

df.info()

     city  orders  revenue
0   Delhi     120    12000
1  Mumbai     200    25000
2   Delhi     150    18000
3   Noida      90     9000
4  Mumbai     180    22000
(5, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   city     5 non-null      object
 1   orders   5 non-null      int64
 2   revenue  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [17]:
import pandas as pd

data = {
    "city": ["Delhi", "Mumbai", "Delhi", "Noida", "Mumbai"],
    "orders": [120, 200, 150, 90, 180],
    "revenue": [12000, 25000, 18000, 9000, 22000]
}

df = pd.DataFrame(data)
df.sort_values("revenue")
print(df.head(2))

     city  orders  revenue
0   Delhi     120    12000
1  Mumbai     200    25000

In [26]:
import pandas as pd

data = {
    "city": ["Delhi", "Mumbai", "Noida"],
    "revenue": [12000, 25000, 9000]
}

df = pd.DataFrame(data, index=["A", "B", "C"])
print(df.loc["B","revenue"])
print(df.iloc[1,0])
print(df.iloc[0,1])

25000
Mumbai
12000

In [34]:
import pandas as pd

data = {
    "product": ["Laptop", "Phone", "Tablet", "Monitor"],
    "price": [50000, 20000, 15000, 12000]
}

df = pd.DataFrame(data)
a = df.sort_values("price",ascending=False)
print(a.head(2))

  product  price
0  Laptop  50000
1   Phone  20000